### PR TITLE
parse_single_rhs receives the 'items' of the row

### PR DESCRIPTION
**Pull request by josepalos**
When parse_single_rhs finds a row with the sense of N, it fails because it tries to print the row with join(items, " ") but items is not received in this function.
This PR corrects this, by sending items to the method.

### CODE REVIEW

**Comment by odow** [comment]
Thanks. Can you add a test so that we don't re-introduce the bug in future?

p.s. The broken test should be fixed by: https://github.com/odow/MathOptFormat.jl/pull/88

**Comment by odow** [comment]
Hey @josepalos, I've merged the fix, so you should just rebase your branch onto the latest master.

**Comment by josepalos** [comment]
> Thanks. Can you add a test so that we don't re-introduce the bug in future?
> 
> p.s. The broken test should be fixed by: #88

I'm new to the Julia language, so it might be a while until I can add the tests. I'll do as soon as I have some free time to learn about them.

**Comment by odow** [comment]
> I'm new to the Julia language

Welcome! Tests are added to the `/test` folder. Then, in the Julia REPL, you can call 
```Julia
Julia> ] test MathOptFormat
```
which runs the code in `test/runtests.jl`.

For this specific problem, you don't need to write Julia tests. You just need to add an example of the malformed model to:
https://github.com/odow/MathOptFormat.jl/tree/master/test/MPS/failing_models

There are actually three cases to account for:
```
NAME
ROWS
 N  c
COLUMNS
    x         c         1
RHS
    rhs       c         1
ENDATA
```

```
NAME
ROWS
 N  c
 G  d
COLUMNS
    x         c         1
    x         d         1
RHS
    rhs       c         1      d      1
ENDATA
```

```
NAME
ROWS
 N  c
 G  d
COLUMNS
    x         c         1
    x         d         1
RHS
    rhs       d         1      c      1
ENDATA
```

**Comment by odow** [comment]
Thanks @josepalos. I cherry-picked your commit in #93.

**Pull request closed without merging**
